### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by kilpatty** [ProjectKnucks/blockBackend#21]
Let's move all our media queries / breakpoints into variables so that things are more standard.

$tablet
$mobile, etc

**Comment by shanejann** [comment]
I think we're good on this. 
- Added a number of color variables (I didn't pull all the hex values we had...Probably still could)
- Navbar and footer heights. Also implemented the contentContainer calculation so use that for the first class in blocks now if it's not there already- that'll ensure the page is always large enough.
- Added media variables for the $tablet and $mobile
