### ISSUE TITLE
Bug with "pie"

### ISSUE THREAD

**Issue by kilpatty** [ProjectKnucks/blockBackend#8]
Some bug with retrieving names that are "CLOSED" in state - need to investigate more. Right now if you search the domain "pie" it breaks our name.js handler.

**Comment by kilpatty** [comment]
Also a lot of other names bug out FYI

**Comment by shanejann** [comment]
info is just null in this case, which kills our pug template...Maybe we should just show an empty state. However, that doesn't actually solve the issue on _why_  `info` is null 🤔
